### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Dogsmoker** [Radon-Club/Radon-Throw#1]
- [x] Command 
- [x] Pickup player 
- [x] Throw player
- [x] Sync between players

Maybe?:
- [ ] Pickup world objects?
- [ ] Throw world objects?
